list1=(x for x in range(11) if x%2==0)
print(list1.__next__())
print(list1.__next__())
print(list1.__next__())
print(list1.__next__())
print(list1.__next__())
print(list1.__next__())
print(list1.__next__())
